### ISSUE TITLE
时间序列阈值问题

### ISSUE THREAD

**Issue by quicksandznzn** [meixinyun/AbnormalDetection#1]
我的想法是用holt-winters预测出一段时间的数据然后和正确的数据来进行对比报警  想了解下阈值函数用那种方式实现合适

**Comment by ieasydevops** [comment]
文中其实列举一不少方式,基本的种策略思想是, 基于历史数据算出一个数据的置信区间,通过实时数据在是否落在置信区间来判断,或者基于置信区间的阈值范围,应用3 sigma 准则来判定
